---
# Terraform Vars
ingress_nginx_external_tfvars:
  namespace: "ingress-external"
  chart:
    repository: "https://kubernetes.github.io/ingress-nginx"
    version: "4.4.0"
    values_files:
    - helm_values_ingress_nginx_external.yml
# Auxiliary variables
ingress_nginx_external_ClassResource_name: "nginx-external"
# Helm Chart values
ingress_nginx_external_helm_values:
  controller:
    tolerations: "{{ default_tolerations }}"
    ingressClassResource:
      name: "{{ ingress_nginx_external_ClassResource_name }}"
      controllerValue: "k8s.io/external-ingress-nginx"
    replicaCount: "1"
    service:
      externalTrafficPolicy: "Local"
    # -- For backwards compatibility with ingress.class annotation, use ingressClass.
    # Algorithm is as follows, first ingressClassName is considered, if not present, controller looks for ingress.class annotation
    ingressClass: "{{ ingress_nginx_external_ClassResource_name }}"
    admissionWebhooks:
      patch:
        tolerations: "{{ default_tolerations }}"
  defaultBackend:
    tolerations: "{{ default_tolerations }}"
