# Terraform TFVars
terraform_tfvars:
  gcp:
    project_id: "{{ gcp_project_id }}"
    region: "{{ gcp_region }}"
  vpc:
    network: "{{ vpc.network }}"
    subnetwork: "{{ vpc.subnetwork }}"
  gke:
    name: "{{ gke_name }}"
    description: "GKE Cluster {{ gke_name }}"
    location: "us-central1-a"
    ip_allocation_policy:
      cluster_ipv4_cidr_block: "{{ gke_cluster_ipv4_cidr_block }}"
      services_ipv4_cidr_block: "{{ gke_services_ipv4_cidr_block }}"
    private_cluster_config:
      enable_private_endpoint: false
      enable_private_nodes: true
      master_ipv4_cidr_block: "{{ gke_master_ipv4_cidr_block }}"
    initial_node_count: 1
    remove_default_node_pool: false
    node_pools:
    - name: "default-pool"
      autoscaling:        
        min_count: "1"
        max_count: "2"
      node_config:
        machine_type: "e2-micro"
        disk_size_gb: "10"
    - name: "tau"
      autoscaling:        
        min_count: "1"
        max_count: "2"
      node_config:
        machine_type: "t2a-standard-1"
        disk_size_gb: "10"
        spot: true
