version: '3'

services:
  poc-gke-envs:
    build: .
    container_name: cte-poc-gke-envs
    hostname: cte-poc-gke-envs
    user: root
    volumes:
    - ~/.ssh:/root/.ssh:ro
    - ~/.kube:/root/.kube
    - ~/.config/gcloud/:/root/.config/gcloud
    - ~/Documents/Automation/:/automation/
    environment:
    - LOGNAME=$LOGNAME
    command: sleep infinity
