---
name: "Manage environment"
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action: plan, apply, destroy'
        required: true
        default: 'plan' 
        type: choice
        options:
        - plan
        - apply
        - destroy
  push:
    paths:
    - 'group_vars/*'
    - 'host_vars/*'
jobs:
  provision:
    name: Manage environment
    runs-on: [ self-hosted ]
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.3
        terraform_wrapper: false
    - name: Install Python 3.8
      run: sudo apt-get install -y python3.8
    - name: Install Ansible 2.12
      run: pip install "ansible-core<=2.12"
    - name: Generate Terraform vars and Backend
      run: ansible-playbook -i inventory.yml --limit dev preparing.yml
    - name: Terraform Init
      run: terraform init -backend-config=config.gcs.tfbackend 
      working-directory: structure/terraform
    - name: Terraform Plan
      run: terraform plan -input=false -out plan.out -var-file="terraform.tfvars.json"
      working-directory: structure/terraform
