---
name: "Manage environment"
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action: plan, apply, destroy'
        required: true
        default: 'plan' 
        type: choice
        options:
        - plan
        - apply
        - destroy
  push:
    paths:
    - 'group_vars/*'
    - 'host_vars/*'
jobs:
  provision:
    name: "Manage environment"
    runs-on: [ self-hosted ]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.3
        terraform_wrapper: false
    - name: Run ansible-lint
      # replace `main` with any valid ref, or tags like `v6`
      uses: ansible-community/ansible-lint-action@main
    - name: Test
      run: ansible --version
    # - name: Terraform Init
    #   run: terraform init -backend-config=../../environments/${{ github.event.inputs.environment }}/${{ github.event.inputs.component }}/backend.hcl
    #   working-directory: terraform/${{ github.event.inputs.component }}
